services:
  #------ NGINX Reverse Proxy ------
  nginx:
    mem_limit: 256m
    mem_reservation: 256m
    container_name: zero_nginx
    image: nginx:latest
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - 80:80
      - 443:443
    depends_on:
      - mysql
    volumes:
      - ./docker/nginx/localhost.crt:/etc/cert/localhost.crt
      - ./docker/nginx/localhost.key:/etc/cert/localhost.key
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - normal

  #------ MySQL DB ------
  mysql:
    image: 'mysql:5.7'
    mem_limit: 512m
    mem_reservation: 512m
    container_name: zero_mysql
    ports:
      - '3306:3306'
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
    volumes:
      - './docker/mysql/init-script.sql:/docker-entrypoint-initdb.d/init.sql'
      - 'mysql_data:/var/lib/mysql'
    command: "--init-file /docker-entrypoint-initdb.d/init.sql"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping"]
      retries: 3
      timeout: 5s
    networks:
      - normal

volumes:
  mysql_data:
    driver: local

networks:
  normal:
    driver: bridge
